#Dataloader
batch_size: 64
buffer_size: null
image_height: 256
image_width: 256
image_channels: 3
seed: 42
lower: -10
upper: 10
limit: 0.1 #set null if for limitations, is a percentage on how many to use

#ModelSpesifications
model_name: akselnet
models:
  akselnet:
    input_shape: [256, 256, 3]
  stiannet:

#Logs and model storage
tensorboard:
  log_dir: logs #also de directory for the best models
