
#Dataloader
batch_size: 10
buffer_size: null
image_height: 256
image_width: 256
image_channels: 3
seed: 42
lower: -10
upper: 10
limit: null #set null if for no limitations

#ModelSpesifications
model_name: akselnet
models:
  akselnet:
    input_shape: [ 256, 256, 3 ]
    loss: 'binary_crossentropy'
    metrics: 'binary_accuracy'


#Logs and model storage
tensorboard:
  log_dir: logs #also de directory for the best models
