#Dataloader
batch_size: 10
buffer_size: null
image_height: 256
image_width: 256
image_channels: 3
seed: 42
lower: -10
upper: 10
limit: 0.1 #set null if for limitations, is a percentage on how many to use

#ModelSpesifications
model_name: "syedanet"
syeda_dataloader: yes
models:
  exampleNet:
    input_shape: [265, 256, 3]
    loss: "binary_crossentropy"
    metrics: "binary_accuracy"

  akselnet:
    input_shape: [256, 256, 3]
    loss: "binary_crossentropy"
    metrics: "binary_accuracy"

  syedanet:
    input_shape: [256, 256, 3]
    loss: "hinge"
    metrics: "binary-accuracy"



#Logs and model storage
tensorboard:
  log_dir: logs #also de directory for the best models
