batch_size: 16
buffer_size: null
image_height: 256
image_width: 256
image_channels: 3
seed: 42
lower: -10
upper: 10
model_name: akselnet
models:
  akselnet:
    input_shape: [ 256, 256, 3 ]
  stiannet:

tensorboard:
  log_dir: logs #also de directory for the best models
limit: 100